apiVersion: batch/v1
kind: Job
metadata:
  name: meshed-test-job
spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - command:
        - /bin/sh
        args:
        - -c
        - psql
        - |
          select * from temp_delete_track_table;
        - -c
        - curl -X POST http://localhost:4191/shutdown
